require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

inherit_from: .rubocop_todo.yml

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 120

