default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: fuzzy_trader_dev

test:
  <<: *default
  database: fuzzy_trader_test

production:
  <<: *default
  database: fuzzy_trader
